hw5/foodcourt/app.py
#!/usr/bin/env python3

from flask import Flask, render_template
from views.menu import v_menu


app = Flask(__name__)

app.register_blueprint(v_menu, url_prefix="/menu")


@app.route("/", methods=["GET"])
def index():
    return render_template("index.html")


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True,
    )

hw5/foodcourt/views/menu.py
#!/usr/bin/env python3

import random
from time import time
from datetime import datetime
from flask import Blueprint, render_template, request

v_menu = Blueprint("v_menu", __name__)

MENU = {
    1: "Чай",
    2: "Кофе",
    3: "Борщ",
    4: "Окрошка",
    5: "Пюре",
    6: "Гречка",
    7: "Макароны",
    8: "Гуляш",
    9: "Котлеты куриные",
    10: "Свинная отбивная",
}

ORDERS = []


@v_menu.route("/", methods=["GET"])
def menu_list():
    return render_template("menu/index.html", menu=MENU)


@v_menu.route("/order/add", methods=["POST"])
def menu_order_add():
    my_order = {
        'id': f'{int(time())}/{int(random.random()*1000)}',
        'time': datetime.now(),
        'address': request.form.get('address'),
        'persons': request.form.get('persons') or 1,
        'food': [],
    }
    for food_id in request.form.getlist('food'):
        if MENU.get(food_id) is None:
            next
        my_order['food'].append(int(food_id))

    ORDERS.append(my_order)
    return render_template("menu/order_done.html", order=my_order)


@v_menu.route("/order/list", methods=["GET"])
def menu_order_list():
    return render_template("menu/order_list.html", orders=ORDERS, menu=MENU)

hw5/foodcourt/templates/menu/index.html
{% extends 'wrappers/base.html' %}

{% block body %}
    <h3>Оформите заказ:</h3>
    <form method="POST" action="{{ url_for('v_menu.menu_order_add') }}">
        <div class="mb-3">
        <label class="form-label">Виберете блюда:</label>
        {% for i in menu %}
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="{{ i }}" id="flexCheckChecked-{{ i }}" name="food">
            <label class="form-check-label" for="flexCheckChecked-{{ i }}">
                {{ menu.get(i) }}
            </label>
        </div>
        {% endfor %}
        </div>
         <div class="mb-3 col-3">
            <label for="form-persons" class="form-label">Укажите количество приборов </label>
            <input type="number" id="form-persons" class="form-control" name="persons" placeholder="1" value="1" required>
        </div>
        <div class="mb-3 col-6">
            <label for="form-address" class="form-label">Укажите адрес доставки </label>
            <input id="form-address" class="form-control" name="address" placeholder="Стамбул" value="" required>
        </div>

        <button class="btn btn-primary" class="form-control" type="submit" value="1">Отправить</button>
    </form>
{% endblock %}

hw5/foodcourt/templates/menu/order_done.html
{% extends 'wrappers/base.html' %}

{% block body %}
    <h3>Ваш заказ принят!</h3>
    <p>Номер вашего заказа: {{ order.get('id') }}</p>
    <br/>
    <a href="{{ url_for('v_menu.menu_list') }}"><<< Сделать ещё заказ</a> |
    <a href="{{ url_for('v_menu.menu_order_list') }}">Посмотреть заказы >>></a>

{% endblock %}

hw5/foodcourt/templates/menu/order_list.html
{% extends 'wrappers/base.html' %}

{% block body %}
    <h3>Список заказов!</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="1">№</th>
                <th colspan="1">Дата заказа</th>
                <th colspan="4">Содержимое заказа</th>
                <th colspan="5">Адрес доставки</th>
                <th colspan="1">Кол-во приборов</th>

            </tr>
        </thead>
        <tbody>
        {% for o in orders | reverse %}
            <tr>
                <td colspan="1">{{ o.get('id') }}</td>
                <td colspan="1">{{ o.get('time') }}</td>
                <td colspan="4">
                    <ul class="">
                    {% for fid in o.get('food') %}
                        <li class="">{{ menu.get(fid) }}</li>
                    {% endfor %}
                    </ul>
                </td>
                <td colspan="5">{{ o.get('address') }}</td>
                <td colspan="1">{{ o.get('persons') }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br/>
    <a href="{{ url_for('v_menu.menu_list') }}">Сделать ещё заказ</a>
{% endblock %}